### ISSUE TITLE
Disruptive and Manual/Complex Tasks

### ISSUE THREAD

**Issue by jamescassell** [MindPointGroup/RHEL7-STIG#119]
We should come up with a convention for items that are not remediated automatically, or items that require manual review.  Preferably, this could be configured both on-the-fly with tags, and statically with variables.

In my opinion, we can't expect a user to read thru all the ansible-playbook output, looking for items that might require intervention.

**Comment by jamescassell** [comment]
Here's my proposal.
The scap-security-guide project labels their remediation tasks with 3 categories: severity, complexity, and disruption.  It seems like a good approach to me:

- I suggest we tag items requiring manual review as `complexity-high` and add a conditional on `rhel7stig_complexity_high: default(no)`.
- I suggest we tag items that can break a system as `disruption-high` and add a conditional on `rhel7stig_disruption_high: default(no)`.

We can then add later `disruption-medium` and `disruption-low` for tasks that are respectively less likely to break something.  Similarly, later add `complexity-medium` and `complexity-low` for tasks depending on how involved the remediation is.  (Specifically, I'm thinking that if, e.g., a remediation requires multiple tasks to succeed, it would get `complexity-medium`.)

**Comment by jamescassell** [comment]
@shepdelacreme yes, I'd also like to add something like rhel7stig_audit_complex and rhel7stig_audit_disruptive as an available hint to the user that something was not remediated.

**Comment by shepdelacreme** [comment]
I'd like to see how much complexity this would add to the role. But I'm not opposed to something like this.

**Comment by defionscode** [comment]
I like this idea. No objections from me.

**Comment by defionscode** [comment]
i just thought of something, we could make a ansible callback plugin that can show manual/not-remediate rules at the end of a playbook run

**Comment by jamescassell** [comment]
The work to mark a task as disruptive is adding 3 lines: 1 tag, 1 conditional, and a check_mode statement.  See #254 for an example of how to make such a change.  Labeling this issue as "accepted proposal" and closing to clear the issue log.
