### ISSUE TITLE
RHEL-07-010010 PATCH gets tripped up by missing files

### ISSUE THREAD

**Issue by lerlacher** [MindPointGroup/RHEL7-STIG#151]
Hello,

I don't know if this is a common problem and it's hard to understand this for me because I do not have in-depth knowledge of RedHat / CentOS / general rpm-based distros but on a fresh install of CentOS 7 from `CentOS-7-x86_64-Minimal-1804.iso` there are lots of missing package files that result in `rpm --setperms` exiting with an error return code.

Example:

```
[root@localhost ~]# rpm --setperms $(rpm -qf /usr/sbin/netreport)
chmod: cannot access ‘/etc/sysconfig/kvm’: No such file or directory
```

This causes RHEL-07-010010 to fail a lot.

Is there something wrong with my CentOS installation or is missing package files normal?

**Comment by jamescassell** [comment]
I can confirm the issue, but I don't generally run into it when running the role, which ignores config files.  I think RHEL 7 supports partial package installation, excluding things like translations.

**Comment by shepdelacreme** [comment]
Hmm...probably a few ways around this like forcing reinstall of the packages with missing files or at least ignoring "No such file" errors on the setperms command. I'll mark this as a low priority bug for now since I don't thing it is a wide spread issue.

**Comment by jamescassell** [comment]
This is a bug in RPM.  `rpm --setugids` or `rpm --setperms` attempts to set the attributes on all files, not just the ones that fail verification.  In some cases, the files may not exist.  I'm working on a workaround.
