### ISSUE TITLE
Ansible STIG Role for RHEL 7

### ISSUE THREAD

**Issue by andysmagana** [MindPointGroup/RHEL7-STIG#154]
I am looking for some help withe the MindPointGroup.RHEL7-STIG role can some one help me understand this part of the read me it state,

rhel7stig_min_ansible_version: 2.1

rhel7stig_cat1_patch: yes
rhel7stig_cat2_patch: yes
rhel7stig_cat3_patch: yes

These variables correspond with the STIG IDs defined in the STIG and allows you to enable/disable specific rules.

PLEASE NOTE: These work in coordination with the cat1, cat2, cat3 group variables. You must enable an entire group in order for the variables below to take effect.

CAT 1 rules
rhel_07_010010: true
rhel_07_010020: true
rhel_07_010290: true
rhel_07_010300: true
rhel_07_010440: true
rhel_07_010450: true
rhel_07_010480: true
rhel_07_010490: true
rhel_07_020000: true
rhel_07_020010: true
rhel_07_020050: true
rhel_07_020060: true

**Comment by shepdelacreme** [comment]
I'm not exactly sure what you need clarification on but here is an explanation of how these variables work.

The variables that look like:
`rhel_07_010010` enable or disable (true/false) specific tasks in the role. Those tasks correspond with remediation items defined in the actual DISA STIG document.

The variables that look like `rhel7stig_cat1_patch` enable or disable entire families of tasks. All tasks or remediation items in the STIG are grouped in one of the following categories: I, II, or III. Thus setting `rhel7stig_cat3_path: no` means that no category 3 tasks will run, regardless whether their corresponding `rhel_07_020060` variable is set to `true` or `false`.

Let us know if that helps.

**Comment by andysmagana** [comment]
Thank you I can understand that now that you explained it. I discovered that I disabled the rhel7stig_cat1_patch: no and rhel7stig_cat2_patch: yes and rhel7stig_cat3_patch: no, after running the role against target server,  I was expecting audit rules to be written in the file  /etc/audit/audit.rules or in /etc/audit/audit.d/audit.rules  but there are no rules written .

**Comment by andysmagana** [comment]
I meant to keep this open until I can get an answer about why audit rules are not being written into /etc/audit/audit.rules.

**Comment by jamescassell** [comment]
@andysmagana the audit rules are written to files under /etc/audit/rules.d/

**Comment by defionscode** [comment]
Closing
