### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by gregdurham** [MindPointGroup/RHEL7-STIG#155]
Hello,
Thank you for your group's efforts in pushing forward security through these ansible roles. They are incredibly helpful. 

What is the current status/state of this project and is this still under active development? 
Is this safe to use in it's current state?
Should this be used in conjunction with or instead of the RHEL7-CIS?

Thank you again!

**Comment by jamescassell** [comment]
The role is fairly mature at this point.  A system hardened by this role will score very well on against the DISA STIG benchmark tool.  Use the devel branch, not master; the latter is severely out of date.

**Comment by gregdurham** [comment]
excellent, thank you very much @jamescassell
