### ISSUE TITLE
role attempts to remediate SSH even if not installed

### ISSUE THREAD

**Issue by jamescassell** [MindPointGroup/RHEL7-STIG#158]
If openssh-server is not installed, none of the SSH remediations need to be performed.  Currently, the role fails out in this case.

**Comment by shepdelacreme** [comment]
Hmm yes I guess the assumption was that people running Ansible are using SSH but of course that is not always the case! We should have a prelim check probably and then skip tasks based on the result of that just like some of the other tasks.
