### ISSUE TITLE
RHEL-07-030360 : removed suid programs and augenrules --load failure

### ISSUE THREAD

**Issue by dirtyharrycallahan** [MindPointGroup/RHEL7-STIG#175]
rules file probably needs to be created from scratch each time. If a suid program added in a previous invocation is removed then augenrules --load will fail due to the non-existing binary. We plan to wipe the file at the start. Sorry corporate policy prevents me from contributing pull requests.

**Comment by jamescassell** [comment]
Wiping the file unconditionally would break impotence. However, there are better ways to do it.

**Comment by jamescassell** [comment]
should be fixed by #211 once it's merged.
