### ISSUE TITLE
Supporting older versions of Ansible

### ISSUE THREAD

**Issue by shepdelacreme** [MindPointGroup/RHEL7-STIG#188]
This is just a general comment to get opinions on how we should handle supporting older Ansible versions. This came to mind because of all the recent pamd module bugs we've run across. Once the pamd tasks are implemented they will run without error but may make unintended changes to the pamd configuration files because of some of the bugs.

i.e. This most recent bug https://github.com/ansible/ansible/pull/47420 will definitely remove leading dashes from any line that has them without even reporting a change happened. If the fix is accepted and it gets backported the only version that will get the backport is 2.7 (maybe 2.6 depending on how Ansible defines "critical issues") so my recommendation to people would be to use 2.7 or newer.

Would this be problematic for the community? Should we take extra steps to skip tasks that don't work with specific versions of Ansible? Thoughts?

**Comment by defionscode** [comment]
Probably better suited as a mailing list discussion but in my opinion we should only guarantee support against the latest stable release this will make maintenance easier. I think it would be good to have create changelog for new updates though (where we can make disclaimers on pamd behavior, etc) and we should probably start cranking out tags again too.

**Comment by jamescassell** [comment]
I'd be against dropping support for ansible 2.4 if it's reasonably easy to continue supporting it.  I intend to look into the pamd issues at some point, as I believe they should be surmountable within what's already there.

Some organizations have rhel-7-server-extras-rpms on their Satellite server but have not seen fit to synchronize the rhel-7-server-ansible-2-rpms repo, and are opposed to installing things from epel.  The rhel-7-server-extras-rpms repo has a version of ansible-2.4.

**Comment by shepdelacreme** [comment]
I'll move/ask this question on the mailing list as well.

But here is the problem with supporting 2.4. It is well out of support by RH or even the Ansible team. i.e. They will not produce or backport any fixes to 2.4 (even security fixes). It boggles my mind that RH has an unsupported product that they own/produce in an official repo like that but it doesn't surprise me. 

The pamd module is one small issue with supporting releases as old as 2.4. Many core things have changed, are being deprecated, etc.

As far as I can tell the many issues with the pamd module were introduced in this extensive rewrite of the module in the stable-2.6 branch. 

https://github.com/ansible/ansible/commit/fabce9810445f3bc11e9cf1b38d9b69a58cd5099#diff-305b0e63652b5c15641b13a5261b9d80

So for pamd purposes I think people are probably ok running the pamd tasks in this role with 2.4 and 2.5 but 2.6 is out. If they run the pamd tasks with 2.5 or 2.6 they are going to get a potentially broken system. i.e. The module as it is right now will make unintended changes to lines in the pamd file that were not targeted by the task and then report no change because the regex is incorrect AND they use `re.search()` instead of `re.match`. We can still fix the module and get stuff backported to 2.7 at this point and then 2.8 will be gtg going forward. However I'm still opposed to spending any significant effort ensuring the role works with anything older than the latest stable release.

**Comment by jamescassell** [comment]
2.4 went EOL this month.  We can get backported fixes for 2.5, 2.6, and 2.7, if needed.

https://access.redhat.com/support/policy/updates/ansible-engine

Red Hat policy is to never delete a package from a repo once published.  CentOS policy is to reset the repo to ground zero once per minor release, but within a minor release, they never delete a package.

**Comment by shepdelacreme** [comment]
2.5 is limited to security fixes. 2.6 is limited to And the below page in the Ansible docs seems to indicate that 2.6 is limited to security and critical bugfixes. We can probably get all current fixes into 2.6 if we hurry.

https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#release-status

I'm still opposed to supporting previous versions of Ansible due to the speed of changes and the potential for a significant amount of additional work down the road. Right now I'd rather be focused on just getting the role fully implemented and not worrying about backwards compatibility issues.

Once the role is fully implemented then the work load will probably slow down a bit so maybe at that time we can consider a policy to support the 3 supported versions of Ansible at all times and then when a version goes EOL we tag a release and then going forward changes/updates to the role aren't expected or required to be compatible with that EOL release.

**Comment by defionscode** [comment]
I do not think the fixes to pamd would be considered for 2.6 it that it's both `preview` and `community` status'd. That means it's out of the core team's hands and the interface isn't promised to be backwards compatible, and the bugs, while potentially capable of breaking something, aren't in themselves security vulnerabilities. As far as this role (and others that have pam stuff) we could always just copy the upstream pamd module into the roles (currently non-existent) `library` directory and still let folks on older version benefit from the newer module's code

I think I agree with @shepdelacreme but I wll say that we wouldnt/shouldnt reject PRs that add backwards compat, we just cant/shouldnt guarantee it since we wont be testing for that within molecule.

**Comment by defionscode** [comment]
Working group decided on supporting current and last stable release only. PRs that add compatibility to older version will not be rejected on that basis alone.
