### ISSUE TITLE
Similar ansible stig project available

### ISSUE THREAD

**Issue by birish2** [MindPointGroup/RHEL7-STIG#22]
Why not collaborate with the https://github.com/openstack/ansible-hardening project instead? Appears to be a lot farther along for RHEL7/Centos7 and very well documented, including why each STIG is implemented or not.

**Comment by shepdelacreme** [comment]
We are familiar with the ansible-hardening project and the work that started it. It is a great project with a different set of goals, methodology, etc. If you are interested in reading about the goals of the [ansible-lockdown](https://github.com/ansible/ansible-lockdown) project and the various supporting roles (i.e this RHEL7 role) feel free to peruse the following links.

[lockdown contributing guidelines](https://github.com/ansible/ansible-lockdown/blob/master/CONTRIBUTING.md)
[lockdown Google group](https://groups.google.com/forum/#!forum/ansible-lockdown)

Thanks!
