### ISSUE TITLE
"rhel_07_020231: true" absent from ./defaults/main.yml

### ISSUE THREAD

**Issue by mpdhavale** [MindPointGroup/RHEL7-STIG#285]
The task:  "HIGH | RHEL-07-020230 | PATCH | The Red Hat Enterprise Linux operating system must be configured so that the x86 Ctrl-Alt-Delete key sequence is disabled" fails because "rhel_07_020231" is not defined.

Is fixed by adding "rhel_07_020231: true" to ./defaults/main.yml.

**Comment by jamescassell** [comment]
Thanks for the report. It was fixed earlier this week by #283

**Comment by mpdhavale** [comment]
I just realized that myself; that’s what I get for not updating. Thank you,
and my apologies.
