### ISSUE TITLE
RHEL-07-030840 kmod audit rules not correct

### ISSUE THREAD

**Issue by JuddTracy-DAS** [MindPointGroup/RHEL7-STIG#299]
The STIG states that the audit rule should be:

-w /usr/bin/kmod -p x -F auid!=4294967295 -k module-change

But the rule that is created is:

-w /usr/bin/kmod -p x -k module-change

**Comment by jamescassell** [comment]
Please confirm you are using the latest version from the "devel" branch on github.  I cannot reproduce the issue.

**Comment by JuddTracy-DAS** [comment]
Sorry, I was using the latest tagged version not the master branch.
