### ISSUE TITLE
RHEL-07-010070 missing rhel7stig_gui tag

### ISSUE THREAD

**Issue by ocontant** [MindPointGroup/RHEL7-STIG#303]
I was expecting to see the "rhel7stig_gui" in the "when condition" of the task.

It is defined indirectly via the vars/main.yml: line 4:  rhel7stig_dconf_available: ...

Would it be a better way to make these condition directly visible to make it simpler to read. If not in the condition, in a tags or comment.  

My goal was to grep "rhel7stig_gui" "gui" to find all task related to a gui for internal exclusion/mitigation documentation.  I missed a few tasks.

Regards

**Comment by jamescassell** [comment]
I'll try to fix it.
