### ISSUE TITLE
STIG V2R6 released

### ISSUE THREAD

**Issue by jeffb4** [MindPointGroup/RHEL7-STIG#307]
16JAN2020, RHEL7 STIG V2R6 was released. Checking previous issues it might be the case that no changes are necessary for `RHEL7-STIG`, if not could the README be updated?

**Comment by jamescassell** [comment]
see https://github.com/MindPointGroup/RHEL7-STIG/issues/297 and https://github.com/MindPointGroup/RHEL7-STIG/pull/295

**Comment by jeffb4** [comment]
Awesome, thanks James
