### ISSUE TITLE
Mounting /home by UUID

### ISSUE THREAD

**Issue by jeffb4** [MindPointGroup/RHEL7-STIG#309]
I am using the RHEL7-STIG role via Packer for creating hardened AWS AMIs that can be used on a multitude of instance types.

A problem I have run into is that at https://github.com/MindPointGroup/RHEL7-STIG/blob/devel/tasks/fix-cat2.yml#L1295 `/home` sees a fstab change from mounting by UUID to device (on my systems).

I can and have easily remediated this locally by changing to `src: "UUID={{ home_mount.uuid }}"` for the src attribute, but I'm interested in a more general solution I can PR.

Is this the kind of situation for which introducing a new role var would be acceptable? Is there another preferred path to solving?

**Comment by jamescassell** [comment]
Feels like a bug in the ansible_mounts fact provided by ansible, but PRs welcome here if you find a good fix.

**Comment by jeffb4** [comment]
It's not so much, just because the `ansible_mounts` fact is agnostic about how the mount was defined in fstab (since it's just getting mtab entries), for instance:

```
            {
                "block_available": 512600,
                "block_size": 4096,
                "block_total": 521216,
                "block_used": 8616,
                "device": "/dev/nvme1n1p1",
                "fstype": "xfs",
                "inode_available": 1047517,
                "inode_total": 1047552,
                "inode_used": 35,
                "mount": "/var/log",
                "options": "rw,seclabel,relatime,attr2,inode64,noquota",
                "size_available": 2099609600,
                "size_total": 2134900736,
                "uuid": "a1c16fb0-4147-4608-9bfa-e3d6961a6972"
            },
```

And I imagine for most users, a device mount is perfectly fine. It affects me when I go between nvme and non-nvme EC2 instance types with the same image, definitely not the common occurrence.

I'll create a fork and flag to see how you all like it, then.

**Comment by jamescassell** [comment]
Probably good to run a task first to just grep for UUID in fstab, and in that case use UUID, otherwise use device. Thanks for expanding your use case.

**Comment by jeffb4** [comment]
Apologies, started working on a flag to control the behavior before I saw your note about scanning `fstab` . PR at https://github.com/MindPointGroup/RHEL7-STIG/pull/310 , let me know if you'd strongly prefer a grep solution
