### ISSUE TITLE
STIG Does Not Fix Items Marked as True

### ISSUE THREAD

**Issue by i3b** [MindPointGroup/RHEL7-STIG#42]
I am attempting to use Ansible 2.4 with the RHEL7-STIG role to harden a CentOS  7 test VM. I understand that this role will not fix all vulnerabilities listed in the STIG but if I'm understanding the code correctly rule rhel_07_010320 is set to true, so my assumption is that fix will be applied. When I audited my system and manually checked by looking at the contents of the PAM file I verified that the fix was not applied. I then went an viewed the corresponding task in the fix-cat2 playbook and it just returns true (command: "true").  Has this fix not been implemented yet or am I misunderstanding how all of this works? I viewed the code for the RHEL6 STIG and there are actual steps to add pam_faillock.

**Comment by dsmorse** [comment]
You are correct that the command true and the tag notimplemented show that the ansible code for that rule is not yet in place.   Am I correct in your reference to the RHEL6 STIG as this: https://github.com/MindPointGroup/RHEL6-STIG/blob/devel/tasks/cat2.yml#L982

If so it looks like the RHEL6 used a PAM module which was include in the role, while I think a RHEL 7 solution should leverage the PAMD module that is now part of ansible http://docs.ansible.com/ansible/latest/pamd_module.html

**Comment by i3b** [comment]
Thanks for the clarification. I was trying to understand if all of the tasks had been implemented or not. I completely agree that the Ansible PAM module would work best for that item, I've actually started to implement that on my local configuration but I didn't want to reinvent the wheel if the work had already been done and I was just missing something.
