### ISSUE TITLE
PAM Modification when using BECOME

### ISSUE THREAD

**Issue by mislek** [MindPointGroup/RHEL7-STIG#55]
We have been trying to use a service account instead of root. We have been able to successfully create a password in the vault and use the ansible password to perform SUDO and run the playbook. It all works until it we make a change to the /etc/pam.d/system-auth or /etc/pam.d/password-auth files. When we make a change such as enabling pamd_faillock.so the playbooks stops running as it can no longer authenticate on the remote servers. In such situation, we are forced to use root to run the playbook.

Please note that the service account is an LDAP account NOT a local account at this time.

**Comment by shepdelacreme** [comment]
Interesting...I'll need to setup a system and tie it to LDAP to test this. Do you know if /etc/pam.d/system-auth or password-auth are already modified from the base settings in the system you are applying it to? I.e. there may be some changes in these file to enable the LDAP auth that then gets overwritten or broken with the faillock changes?

**Comment by defionscode** [comment]
@mislek can you share the changes? like what do system-auth and password-auth look like exactly in the broken state? Or is any presence of pamd_faillock.so enough?

**Comment by BryanJeterAL** [comment]
Sounds like their changes are blocking their LDAP service account from SUDO access at least temporarily.  Since pam file changes are immediate, does Ansible have a way to re-authenticate mid playbook?  If not, perhaps pam file changes should be done last?

**Comment by jamescassell** [comment]
This was fixed in #199 (reposition pam_faillock.so, allow domain auth to succeed).  Let us know if that didn't fix it.
