### ISSUE TITLE
grub2_hash broken with RHEL7 stock python-passlib

### ISSUE THREAD

**Issue by jamescassell** [MindPointGroup/RHEL7-STIG#58]
[rhel7 ~]$ rpm -q python-passlib
python-passlib-1.6.5-2.el7.noarch

This role fails due to the required version of passlib.

This should be a trivial fix.  I've added comments here:
https://github.com/MindPointGroup/RHEL7-STIG/pull/23

**Comment by shepdelacreme** [comment]
@jamescassell I think I've addressed this issue in #59 let me know what you think once it passes CI.

Thanks!

**Comment by jamescassell** [comment]
@shepdelacreme PR #59 looks good to me.

**Comment by shepdelacreme** [comment]
Thanks! Closing this issue.
