### ISSUE TITLE
Bad modprobe.d syntax in RHEL-07-020100 and RHEL-07-020101

### ISSUE THREAD

**Issue by lerlacher** [MindPointGroup/RHEL7-STIG#62]
This task:

https://github.com/MindPointGroup/RHEL7-STIG/blob/df72d02aaa8d20bffd2270a2c61266af23cbb16b/tasks/fix-cat2.yml#L620-L635

Adds `^blacklist usb-storage$` to `/etc/modprobe.d/blacklist.conf`.

This is not valid `modprobe.d` syntax and is probably the result of a copy-paste-error.

**Comment by shepdelacreme** [comment]
Looks like the following line needs fixing as well.
https://github.com/MindPointGroup/RHEL7-STIG/blob/0050f5ef4f42842590d9f465808641718e6eb8ec/tasks/fix-cat2.yml#L637-L652
