### ISSUE TITLE
minimum ansible version

### ISSUE THREAD

**Issue by jamescassell** [MindPointGroup/RHEL7-STIG#68]
PR #61 introduced the include_tasks directive, which was intruduced in ansible 2.4.  Since that is the verison currenly shipping with RHEL, do we want to upgrade the minimum supported version to 2.4?  I've currently got a PR in the works that conditionalizes on ansible version, which wouldn't be necessary if the minimum is 2.4.

**Comment by mikerenfro** [comment]
I don't have any investment in older Ansible versions (only got into this after 2.4 was released).

**Comment by shepdelacreme** [comment]
Yes I think we should update the min version to 2.4

**Comment by jamescassell** [comment]
The only thing I can think of is if someone is still trying to manage RHEL 5 from the same box.  That would require 2.3.  I imagine that's a rare use case.

**Comment by shepdelacreme** [comment]
Min version updated to 2.4 in #97
