### ISSUE TITLE
running fix_cat2.yml causes centos yum to fail

### ISSUE THREAD

**Issue by kbroughton** [MindPointGroup/RHEL7-STIG#9]
I'm guessing it has dis-trusted centos repos or placed a restriction on certs too high for standard servers.  I would expect that the playbook work on centos boxes.

"It was impossible to connect to the CentOS servers.
This could mean a connectivity issue in your environment, such as the requirement to configure a proxy,
or a transparent proxy that tampers with TLS security, or an incorrect system clock.
Please collect information about the specific failure that occurs in your environment,
using the instructions in: https://access.redhat.com/solutions/1527033 and create a bug on https://bugs.centos.org/"

The last successful task and first failure are

TASK [RHEL7-STIG : MEDIUM | RHEL-07-040250 | PATCH | The operating system must protect against or limit the effects of Denial of Service (DoS) attacks by validating the operating system is implementing rate-limiting measures on impacted network interfaces.] ***
Thursday 23 February 2017  10:31:35 -0600 (0:00:01.433)       0:11:13.850 *****
ok: [34.*.*.14]

TASK [RHEL7-STIG : MEDIUM | RHEL-07-040260 | PATCH | All networked systems must have SSH installed.] ***
Thursday 23 February 2017  10:31:38 -0600 (0:00:02.325)       0:11:16.175 *****
fatal: [34.*.*.14]: FAILED! => {"changed": false, "failed": true, "msg": "http://download.draios.com/stable/rpm/x86_64/repodata/repomd.xml.asc: [Errno 14] HTTP Error 403 - Forbidden\nTrying other mirror.\nTo address this issue please refer to the below knowledge base article\n\nhttps://access.redhat.com/solutions/69319\n\nIf above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/\n\n\n\n One of the configured repositories failed (Draios),\n and yum doesn't have enough cached data to continue. At this point the only\n safe thing yum can do is fail. There are a few ways to work \"fix\" this:\n\n     1. Contact the upstream for the repository and get them to fix the problem.\n\n     2. Reconfigure the baseurl/etc. for the repository, to point to a working\n        upstream. This is most often useful if you are using a newer\n        distribution release than is supported by the repository (and the\n        packages for the previous distribution release still work).\n\n     3. Disable the repository, so yum won't use it by default. Yum will then\n        just ignore the repository until you permanently enable it again or use\n        --enablerepo for temporary usage:\n\n            yum-config-manager --disable draios\n\n     4. Configure the failing repository to be skipped, if it is unavailable.\n        Note that yum will try to contact the repo. when it runs most commands,\n        so will have to try and fail each time (and thus. yum will be be much\n        slower). If it is a very temporary problem though, this is often a nice\n        compromise:\n\n            yum-config-manager --save --setopt=draios.skip_if_unavailable=true\n\nfailure: repodata/repomd.xml.asc from draios: [Errno 256] No more mirrors to try.\nhttp://download.draios.com/stable/rpm/x86_64/repodata/repomd.xml.asc: [Errno 14] HTTP Error 403 - Forbidden\n", "rc": 1, "results": []}

**Comment by kbroughton** [comment]
We fixed by changing back to zero the items in bold.
There should be a conditional check to not do this for centos.

[root@ip-10-0-100-60 ~]# cat /etc/yum.conf
[main]
**repo_gpgcheck=1**
**localpkg_gpgcheck=1**
cachedir=/var/cache/yum/$basearch/$releasever
keepcache=0
debuglevel=2
logfile=/var/log/yum.log
exactarch=1
obsoletes=1
**gpgcheck=1**
plugins=1
installonly_limit=5
bugtracker_url=http://bugs.centos.org/set_project.php?project_id=23&ref=http://bugs.centos.org/bug_report_page.php?category=yum
distroverpkg=centos-release

**Comment by shepdelacreme** [comment]
The gpgcheck settings definitely work with CentOS. This seems more likely an issue with the Draios repo that is causing the specific error. Can you share your repo configuration for the Draios repo? Also have you imported the GPG for that repo?

In the install instructions from the Sysdig site it looks like it has you import a key.
```
rpm --import https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public  
curl -s -o /etc/yum.repos.d/draios.repo https://s3.amazonaws.com/download.draios.com/stable/rpm/draios.repo
```

**Comment by shepdelacreme** [comment]
Ok this is definitely related to the draios repo. They do not have a repo signing key for the `repomd.xml` file published in their repo. So when you enable `repo_gpgcheck` globally it automatically looks for `repomd.xml.asc` which is supposed to sit next to their `repomd.xml` file and can't find it. 

I'm going to close this issue and the related PR you submitted since this is an issue with the Draios repo specifically. For reference...you can leave `repo_gpgcheck` enabled globally and just set it in the Draios repo file to bypass this issue without weakening security for all your repos.

i.e. in `/etc/yum.repos.d/draios.repo` set
```
repo_gpgcheck=0
```

**Comment by kbroughton** [comment]
thanks.  confirmed.

**Comment by matts-mpg** [comment]
Recommend reopening this as RH is still not providing signed repo data. See here:
https://access.redhat.com/solutions/2850911
https://github.com/OpenSCAP/scap-security-guide/issues/1596

This should be considered a bug and removed from auto-fixing for the time being.

**Comment by shepdelacreme** [comment]
The fix is disabled by default in this role.

See: https://github.com/MindPointGroup/RHEL7-STIG/blob/c4673bc66a20305dd996d5a96c6ce4f6c160bf7f/defaults/main.yml#L23-L24

**Comment by matts-mpg** [comment]
My bad.
