### ISSUE TITLE
STIG Version 1 Release 4  Jan 26 2018 Changes

### ISSUE THREAD

**Issue by shepdelacreme** [MindPointGroup/RHEL7-STIG#95]
Version 1 Release 4 of the STIG was released on Jan 26 2018. These are the relevant changes:
**New STIG IDs**
- [x] RHEL-07-010062 - GUI - Added a requirement to configure gnome desktop screensaver lock setting
- [x] RHEL-07-010101 - GUI - Added a requirement to configure the gnome desktop screensaver idle setting
- [x] RHEL-07-030819 - Added a new auditd rule requirement to audit "create_module" command
- [x] RHEL-07-030821 - Added a new auditd rule requirement to audit "finit_module" command

**Removed STIG IDs**
- [x] RHEL-07-041004 - Removed since 010500 covers all users
- [x] RHEL-07-010080 - GUI - Removed since the gnome/dconf config item was invalid

**Updated STIG IDs**
- [ ] RHEL-07-010030 - GUI - Updated fix text for dconf
- [ ] RHEL-07-010081 - Updated rule title
- [ ] RHEL-07-010082 - Updated rule title
- [ ] RHEL-07-010050 - Removed "short banner" must use full banner
- [ ] RHEL-07-010100 - GUI - Updated example check content output. Updated fix command for dconf
- [ ] RHEL-07-010110 - GUI - Updated finding statement and fix command - dconf
- [x] RHEL-07-010119 - Updated grep command and finding statement. pam.d pwquality retries
- [x] RHEL-07-010480 - Updated finding statement and superusers account setting requirements
- [x] RHEL-07-010490 - Updated finding statement and superusers account setting requirements
- [ ] RHEL-07-020220 - Fixed typos in check content
- [x] RHEL-07-020320 - Removed -xdev option from check command
- [x] RHEL-07-020330 - Removed -xdev option from check command
- [x] RHEL-07-020640 - Updated check content and finding statement
- [x] RHEL-07-020650 - Updated check content statement
- [x] RHEL-07-021350 - Removed wording from fix requiring prelink be disabled and GRUB config instructions.
- [x] RHEL-07-030360 - Corrected command in fix text for auditd rule.
- [ ] RHEL-07-030370 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030380 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030390 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030400 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030410 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030420 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030430 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030440 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030450 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030460 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030470 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030480 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030490 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030500 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030510 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030520 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030530 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030540 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030550 - Updated grep command and fix explanation - auditd rules
- [x] RHEL-07-030640 - Updated command path in check/fix instructions - auditd rules
- [x] RHEL-07-030680 - Updated command path in check/fix instructions - auditd rules
- [ ] RHEL-07-030740 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030820 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030830 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030880 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030890 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030900 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030910 - Updated grep command and fix explanation - auditd rules
- [ ] RHEL-07-030920 - Updated grep command and fix explanation - auditd rules
- [x] RHEL-07-040320 - Updated check command for clientaliveinterval and value range
- [x] RHEL-07-040340 - Not Applicable if redhat release is 7.4 or newer
- [x] RHEL-07-040390 - Not Applicable if redhat release is 7.4 or newer
- [x] RHEL-07-040650 - Updated command path in check and fix content
- [x] RHEL-07-040690 - Updated requirement vsftpd vs lsftpd
- [x] RHEL-07-040710 - Updated typos in check and fix content
- [x] RHEL-07-041002 - Updated ssd config file path in check/fix content
- [x] RHEL-07-041003 - Updated check instructions - PAM config

**Comment by jamescassell** [comment]
These two should be fine because we probe each local mount:
- RHEL-07-020320
- RHEL-07-020330

This one looks fine:
- RHEL-07-010119

These are fine:
- RHEL-07-020640
- RHEL-07-020650

This is fine:
- RHEL-07-030360

These two look fine:
- RHEL-07-030640
- RHEL-07-030680

The rest of the auditd rules are probably fine.

This is fine because we don't allow customization:
- RHEL-07-040320

This looks fine:
- RHEL-07-040650

Fine:
- RHEL-07-040710

Looks fine:
- RHEL-07-041002

notimplemented (no title change) therefore, fine:
- RHEL-07-041003

**Comment by fxfitz** [comment]
Is there planned release timeline of version 1?

**Comment by shepdelacreme** [comment]
We don't have a solid date for a planned v1 release. Since this is a community project right now work is completed as contributors have time. However, I'd like to cut a 1.0 release once we have all the STIG items addressed in "some way". I.e There are no more `command: true` or `- notimplemented` tasks left in the role and we are up to date with the latest STIG revision. This doesn't mean every single STIG item is remediated by the role, obviously there are things we can't or don't want to fix automatically. Just that each item is addressed in some way.

I actually think we are very close to that point with this role. As I get some time between now and this fall I plan to scrub through this role to determine work that is remaining.

**Comment by johannes-cabal** [comment]
Hey all, haven't contributed in a long time. Is this the only items preventing a "1.0 release"? If so, I can get cracking on helping to implement. 

Regarding the "command: true" and "not implemented", would it be better to aggregate those items into a "not-implemented.yml" and move items over to the respective fix/audit tasks as they're either implemented, elsewise retaining those items in "not-implemented", whether by a single file or per category?

**Comment by jamescassell** [comment]
@johannes-cabal I think this list is just the items that were updated in V1R4.  You'd have to look at fix-cat{1,2.3}.yml files for instances of "notimplemented" or "command: true" to see a complete list of items that remain to be implemented.  Probably the most hairy one is enforcing SELinux user contexts.

**Comment by shepdelacreme** [comment]
Yes...what @jamescassell said. As a follow on...I don't think we should begin moving notimplemented items out of the fix task files. And the old audit task files are completely removed/deprecated at this point. We no longer maintain separate audit tasks for the purpose of checking on the state of a STIG item.

I use this command to pull a checklist of items that are notimplemented...its not perfect (i.e. it bombs out on the first match  RHEL-07-010030 for some reason) but works pretty well.

```
awk -F '|' -v RS='' '/- name:.*- notimplemented/ { print "- [ ] "$2 " - " substr($4, 1, length($4)-1); }' tasks/fix-cat{1,2,3}.yml > tempfile
```

Here is the current list.
- [ ]  RHEL-07-010030  -  The operating system must display the Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a graphical user logon.
- [ ]  RHEL-07-010040  -  The operating system must display the approved Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a graphical user logon.
- [ ]  RHEL-07-010060  -  The operating system must enable a user session lock until that user re-establishes access using established identification and authentication procedures.
- [ ]  RHEL-07-010061  -  The operating system must uniquely identify and must authenticate users using multifactor authentication via a graphical user logon.
- [ ]  RHEL-07-010062  -  The operating system must prevent a user from overriding the screensaver lock-enabled setting for the graphical user interface.
- [ ]  RHEL-07-010070  -  The operating system must initiate a screensaver after a 15-minute period of inactivity for graphical user interfaces.
- [ ]  RHEL-07-010081  -  The operating system must set the lock delay setting for all connection types.
- [ ]  RHEL-07-010082  -  The operating system must set the session idle delay setting for all connection types.
- [ ]  RHEL-07-010100  -  The operating system must initiate a session lock for the screensaver after a period of inactivity for graphical user interfaces.
- [ ]  RHEL-07-010101  -  The operating system must prevent a user from overriding the screensaver idle-activation-enabled setting for the graphical user interface.
- [ ]  RHEL-07-010110  -  The operating system must initiate a session lock for graphical user interfaces when the screensaver is activated.
- [ ]  RHEL-07-010500  -  The operating system must uniquely identify and must authenticate organizational users (or processes acting on behalf of organizational users) using multifactor authentication.
- [ ]  RHEL-07-020020  -  The operating system must prevent non-privileged users from executing privileged functions to include disabling, circumventing, or altering implemented security safeguards/countermeasures.
- [ ]  RHEL-07-020600  -  All local interactive users must have a home directory assigned in the /etc/passwd file.
- [ ]  RHEL-07-020680  -  All files and directories contained in local interactive user home directories must have mode 0750 or less permissive.
- [ ]  RHEL-07-020710  -  All local initialization files must have mode 0740 or less permissive.
- [ ]  RHEL-07-020720  -  All local initialization files must have mode 0740 or less permissive.
- [ ]  RHEL-07-020730  -  Local initialization files must not execute world-writable programs.
- [ ]  RHEL-07-021010  -  File systems that are used with removable media must be mounted to prevent files with the setuid and setgid bit set from being executed.
- [ ]  RHEL-07-021030  -  All world-writable directories must be group-owned by root, sys, bin, or an application group.
- [ ]  RHEL-07-021040  -  The umask must be set to 077 for all local interactive user accounts.
- [ ]  RHEL-07-021700  -  The system must not allow removable media to be used as the boot loader unless approved.
- [ ]  RHEL-07-030300  -  The operating system must off-load audit records onto a different system or media from the system being audited.
- [ ]  RHEL-07-040100  -  The host must be configured to prohibit or restrict the use of functions, ports, protocols, and/or services, as defined in the Ports, Protocols, and Services Management Component Local Service Assessment (PPSM CLSA) and vulnerability assessments.
- [ ]  RHEL-07-040180  -  The operating system must implement cryptography to protect the integrity of Lightweight Directory Access Protocol (LDAP) authentication communications.
- [ ]  RHEL-07-040190  -  The operating system must implement cryptography to protect the integrity of Lightweight Directory Access Protocol (LDAP) communications.
- [ ]  RHEL-07-040200  -  The operating system must implement cryptography to protect the integrity of Lightweight Directory Access Protocol (LDAP) communications.
- [ ]  RHEL-07-040510  -  The operating system must protect against or limit the effects of Denial of Service (DoS) attacks by validating the operating system is implementing rate-limiting measures on impacted network interfaces.
- [ ]  RHEL-07-040750  -  The Network File System (NFS) must be configured to use RPCSEC_GSS.
- [ ]  RHEL-07-040810  -  The system's access control program must be configured to grant or deny system access to specific hosts and services.
- [ ]  RHEL-07-041003  -  The operating system must implement certificate status checking for PKI authentication.
- [ ]  RHEL-07-021600  -  The file integrity tool must be configured to verify Access Control Lists (ACLs).
- [ ]  RHEL-07-021610  -  The file integrity tool must be configured to verify extended attributes.
- [ ]  RHEL-07-040600  -  For systems using DNS resolution, at least two name servers must be configured.

**Comment by shepdelacreme** [comment]
Closing this since V2 R1 supersedes this.
